### PR TITLE
Fix: UInt160.Parse & ParseHelper

### LINKED ISSUE #1447: UnitTests cannot pass
Stack Trace:
> TestParseUInt160 (17ms): Error Message: Test method Neo.SmartContract.Framework.UnitTests.UIntTest.TestParseUInt160 threw exception:
      Neo.SmartContract.Testing.Exceptions.TestException: An unhandled exception was thrown. Invalid hex character. ---> Neo.VM.VMUnhandledException: An unhandled e
      xception was thrown. Invalid hex character.
      Stack Trace:
         at Neo.VM.JumpTable.ExecuteThrow(ExecutionEngine engine, StackItem ex)
         at Neo.VM.ExecutionEngine.ExecuteNext()
      --- End of inner exception stack trace ---
         at Neo.SmartContract.Testing.TestEngine.Execute(Script script, Int32 initialPosition, Action`1 beforeExecute) in src/neo-devpack-dotnet/src/Neo.
      SmartContract.Testing/TestEngine.cs:line 646
         at Neo.SmartContract.Testing.SmartContract.Invoke(String methodName, Object[] args) in src/neo-devpack-dotnet/src/Neo.SmartContract.Testing/Smar
      tContract.cs:line 79
         at Neo.SmartContract.Testing.Extensions.MockExtensions.<>c__DisplayClass5_0`1.<MockFunction>b__1(IInvocation invocation) in src/neo-devpack-dotn
      et/src/Neo.SmartContract.Testing/Extensions/MockExtensions.cs:line 116
         at InvokeStub_Func`2.Invoke(Object, Span`1)
         at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
      --- End of stack trace from previous location ---
         at Moq.Extensions.InvokePreserveStack(Delegate del, IReadOnlyList`1 args) in /_/src/Moq/Extensions.cs:line 163
         at Moq.MethodCall.<>c__DisplayClass23_0.<SetReturnComputedValueBehavior>b__0(IInvocation invocation) in /_/src/Moq/MethodCall.cs:line 255
         at Moq.Behaviors.ReturnComputedValue.Execute(Invocation invocation) in /_/src/Moq/Behaviors/ReturnComputedValue.cs:line 22
         at Moq.MethodCall.ExecuteCore(Invocation invocation) in /_/src/Moq/MethodCall.cs:line 109
         at Moq.Setup.Execute(Invocation invocation) in /_/src/Moq/Setup.cs:line 84
         at Moq.FindAndExecuteMatchingSetup.Handle(Invocation invocation, Mock mock) in /_/src/Moq/Interception/InterceptionAspects.cs:line 95
         at Moq.Mock.Moq.IInterceptor.Intercept(Invocation invocation) in /_/src/Moq/Interception/Mock.cs:line 17
         at Moq.CastleProxyFactory.Interceptor.Intercept(IInvocation underlying) in /_/src/Moq/Interception/CastleProxyFactory.cs:line 107
         at Castle.DynamicProxy.AbstractInvocation.Proceed()
         at Castle.Proxies.Contract_UIntProxy.ParseUInt160(String value)
         at Neo.SmartContract.Framework.UnitTests.UIntTest.TestParseUInt160() in src/neo-devpack-dotnet/tests/Neo.SmartContract.Framework.UnitTests/UIntT
      est.cs:line 57
         at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
         at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)

### PR DESCRIPTION
**Pull request by Wi1l-B0t**
Fix #1447 introduced by #1436.

### CODE REVIEW

File: src/Neo.SmartContract.Framework/Helpers/ParseHelper.cs [hunk 1]
```diff
@@ -22,27 +22,21 @@ private static int GetHexPrefixLength(byte[] valueBytes)
...
-            }
+                throw new FormatException("Invalid hex string length.");
 
             var expectedLength = (valueBytes.Length - offset) / 2;
-            result = new byte[expectedLength];
-
+            var result = new byte[expectedLength];
             for (int i = 0; i < expectedLength; i++)
             {
                 byte high = FromHexByte(valueBytes[offset + i * 2]);
```
Comment (Wi1l-B0t) [inline src/Neo.SmartContract.Framework/Helpers/ParseHelper.cs]: `FromHexByte` may throw exception.

**Review by Jim8y — APPROVED** [review]
