### PR TITLE
Fix StorageMap.GetObject

### LINKED ISSUE #659: StorageMap.GetObject should return null if the key is missing
GetObject throws if the key is missing. It should return null instead

### PR DESCRIPTION
**Pull request by erikzhang**
Fix #659

### CODE REVIEW

File: src/Neo.SmartContract.Framework/Services/StorageMap.cs [hunk 1]
```diff
@@ -107,12 +107,16 @@ public class StorageMap
 
         public object GetObject(ByteString key)
```
Comment (devhawk) [inline src/Neo.SmartContract.Framework/Services/StorageMap.cs:108]: Code looks good, but why do we have to duplicate it? Can't byte[] implicitly convert to ByteString or vis versa?

**Review by devhawk — APPROVED** [review]

**Review by shargon — APPROVED** [review]
